### ISSUE TITLE
자보 혹은 커멘트 수정 시에  로그 남기기

### ISSUE THREAD

**Issue by sparcsJara** [sparcs-kaist/zabo-api#64]
zabo, comment, recomment의 내용이 수정될 때,( delete, update) 그 내용을 남겨야될 필요성이 있다.

다음 세 모델의 디비 내용이 변경될 때 content 변경에 관한 로그를 데이터베이스에 남기는 것이 필요하다.
- zabo
- comment
- recomment

**Comment by Suckzoo** [comment]
@sparcsJara zabo 모델은 히스토리 유지하는 데 찬성이긴 한데, 댓글이나 대댓글까지 히스토리를 챙겨야 할까요? 수정 못 하게 막아버리는 건 어떤지?

**Comment by lopun** [comment]
개인적으로는 수정 자체는 할 수 있는게 좋은것같아요! 히스토리는 추후에 뭔가 일이 터졌을때 필요하려나..? 그 부분에 관해서는 잘 모르겠습니다.

**Comment by sparcsJara** [comment]
아라 보면 댓글을 모욕적으로 다는 사례를 몇 개 경험해봐서요. 추후에 이런 댓글들에 대해 요청이 들어왔는데 수정되서 보여줄 수 없는 건 문제가 있을 것 같습니다. 그래서 히스토리를 남겨야 된다고 생각합니다.

**Comment by Suckzoo** [comment]
https://github.com/sparcs-kaist/zabo-api/pull/65
